### ISSUE TITLE
讨论： 关于专有名词以及引用文档的翻译

### ISSUE THREAD

**Issue by ray-g** [go-internals-cn/go-internals#4]
我看到有些专有名词以及引用的文档没有翻译。
于是就此请各位讨论一下，关于一些专有名词以及引用文档是否需要翻译。
如果需要翻译，怎样比较合适。

专有名词比如， interface， receiver 等之类的在golang或在业界有固定意义的名词收否需要翻译？

个人的建议是 翻译并带上英文单词。
比如， 接口（interface）， 接收者（receiver）

关于引用的文档以及代码中大段的注释， 个人也建议 翻译并保留英文在一旁。

不知各位老大意下如何？

**Comment by cch123** [comment]
专有名词我觉得没必要翻译，interface 和 receiver 大家都看得懂
拿 receiver 来说，也没有标准翻译，什么接收器，接收者都能译，要是读的人读到的东西和之前见的不太一样，反而还比较别扭，非要翻成中文那是中文出版物的要求了

引用部分保留英文主要是为了方便阅读的人去和原始文档对应，当然，翻译加原文也可以接受~
你有意向的话欢迎 pr~

**Comment by ray-g** [comment]
OK，这两天我把引用部分翻译完了提个pr

**Comment by ghost** [comment]
专有名词

我建议不翻译，专有名词本身就是对某一新概念的抽象描述，一般情况下这个新概念在中文中是没有的，也就是没有一个汉语名词可以准确概括这一新概念的准确含义。

原文引用

我觉得可以翻译。

@ray-g @cch123

**Comment by ray-g** [comment]
我同意专有名词不翻译。

引用翻译并保留原文，同时可以适当翻译代码中的注释。

如果大家没意见的话，就可以关了这个issue了。

我这两天把引用翻译完后提个pr

**Comment by cch123** [comment]
看来大家想法一致，关了～
