### ISSUE TITLE
Gitbook 的链接依然是英文版

### ISSUE THREAD

**Issue by ray-g** [go-internals-cn/go-internals#5]
@cch123 是需要你publish到gitbook上，然后更新一下链接吧？

**Comment by cch123** [comment]
@ray-g ，我看原作者是整了个分支。。
这个感觉要是原分支改了想同步还挺麻烦的吧。。

顺便，要是有兴趣贡献之后的翻译的话，
可以把微信给我，拉你进翻译群~

**Comment by ray-g** [comment]
@cch123 好啊，我微信 Ray__G, 两个下划线

**Comment by ray-g** [comment]
我没太看明白原作者为什么要在那个分支上大动layout，但是又没有merge回master...等等看作者下一步怎么处理再跟着动吧...

**Comment by ray-g** [comment]
已publish 中文gitbook #6 
Close this.
